/* Edit portfolio content here, then run tools/build.cjs to refresh the static pages. */
const site = {
  name: 'Jignesh Gadgi',
  title: 'AI-Powered UI/UX Designer',
  email: 'jigneshgadgi1929@gmail.com',
  contactIsPlaceholder: false,
  cvUrl: null, // Set to your CV PDF path, e.g. assets/Jignesh-Gadgi-CV.pdf, then rebuild.
  statistics: [
    { value: '3+', label: 'Years of experience', description: 'Creating thoughtful web and mobile experiences.' },
    { value: '35+', label: 'Projects completed', description: 'Across UI/UX, product, and visual design.' },
    { value: '100%', label: 'Client satisfaction', description: 'Thoughtful collaboration. Satisfying results.' },
  ],
  location: 'India',
  timeZone: 'Asia/Kolkata',
  url: 'https://example.com', // Replace with your published domain.
  socials: { LinkedIn: 'https://www.linkedin.com/in/jignesh-ui-ux', Behance: null, Dribbble: null, Instagram: null },
};

const projects = [
  { id: 'fitness-live', previewUrl: null, title: 'Fitness Live', category: 'UI/UX · Mobile app', year: '2026', description: 'A little movement. A better everyday.', image: 'assets/images/fitness-live.svg', heroImage: 'assets/images/Hero image.png', link: 'projects/fitness-live.html', services: ['User experience', 'Interface design', 'Prototyping'], color: '#dadf8a', headline: 'Making room for a healthier everyday.', overview: 'An illustrative fitness and yoga app concept that turns an overwhelming choice of workouts into a simple daily ritual. Personal recommendations meet a calm, encouraging interface.', challenge: 'How might we help someone choose a workout that fits their energy, ability, and time — without making exercise feel like another obligation?', approach: 'Start with the moment of decision. A short check-in leads to a focused daily plan, with clear duration, difficulty, and guidance before a session begins.', solution: 'A personal dashboard, a discoverable session library, and an approachable progress view. The visual system pairs warm yellow with strong typography to keep the experience energetic and clear.', principles: ['One clear next step', 'Progress without pressure', 'Guidance at the right moment'] },
  { id: 'riderly', previewUrl: null, title: 'Riderly', category: 'Product design · Mobility', year: '2025', description: 'Less waiting. More getting there.', image: 'assets/images/riderly.svg', link: 'projects/riderly.html', services: ['Product strategy', 'Mobile design', 'Interaction design'], color: '#d9d5ee', headline: 'A smoother way from here to there.', overview: 'An illustrative ride-sharing concept focused on the small moments that build confidence: knowing the fare, finding the pickup point, and understanding what happens next.', challenge: 'How might we reduce uncertainty between booking a ride and meeting a driver, especially in an unfamiliar location?', approach: 'Organize the journey around three decisions: destination, ride choice, and pickup. Keep the route and price visible as the user moves through each step.', solution: 'A map-led interface with clear pickup guidance, transparent ride options, and a persistent trip status. A soft lilac palette makes a busy urban journey feel more composed.', principles: ['Clarity before commitment', 'Visible trip status', 'A confident pickup'] },
  { id: 'bloodconnect', previewUrl: null, title: 'BloodConnect', category: 'UI/UX · Healthcare', year: '2025', description: 'A small connection. A life-changing difference.', image: 'assets/images/bloodconnect.svg', link: 'projects/bloodconnect.html', services: ['User journeys', 'Accessible UI', 'Mobile design'], color: '#f2b8ad', headline: 'Connecting people when it matters most.', overview: 'An illustrative blood donation platform concept that helps people discover nearby donation opportunities and understand the next step with less friction.', challenge: 'How might we make a time-sensitive request easy to understand while keeping important context visible and the experience considerate?', approach: 'Give requests a consistent information order: blood group, location, timing, and contact pathway. Use plain language and predictable actions throughout.', solution: 'A request feed, clear donation center details, and a guided donor profile. The concept emphasizes readable information and visible status; real deployment would require clinical and privacy review.', principles: ['Human language first', 'The right detail, in order', 'Accessible by design'] },
  { id: 'iiot', previewUrl: null, title: 'IIoT Smart Equipment', category: 'Product design · Dashboard', year: '2024', description: 'Complex operations. Clear decisions.', image: 'assets/images/iiot.svg', link: 'projects/iiot.html', services: ['Information architecture', 'Dashboard design', 'Design systems'], color: '#c9d9ce', headline: 'Turning equipment data into a clear next step.', overview: 'An illustrative industrial monitoring interface that gives operations teams a readable view of equipment health, active alerts, and performance trends.', challenge: 'How might we bring useful signals forward when teams have many machines and a limited amount of time to investigate them?', approach: 'Separate an at-a-glance overview from detailed diagnostics. Group equipment by status and make the relationship between alerts and trends explicit.', solution: 'A structured overview with status summaries, readable charts, and equipment-level detail. Consistent visual components create a foundation for scaling the interface.', principles: ['Signal before noise', 'Overview to detail', 'Consistent status language'] },
  { id: 'watch-commerce', previewUrl: null, title: 'Watch Commerce', category: 'Web design · E-commerce', year: '2024', description: 'An appreciation for the finer details.', image: 'assets/images/watch-commerce.svg', link: 'projects/watch-commerce.html', services: ['Art direction', 'E-commerce UX', 'Responsive design'], color: '#d3d3ce', headline: 'A considered experience for timeless objects.', overview: 'An illustrative watch storefront exploring how editorial art direction and clear shopping patterns can work together without compromising either.', challenge: 'How might we create room for craftsmanship and storytelling while keeping product discovery and purchase straightforward?', approach: 'Use large product views, restrained type, and a deliberate content rhythm. Bring material, dimensions, and delivery details into the decision-making flow.', solution: 'A focused collection page and a product detail system that adapts across screens. The design lets the object lead while keeping practical information close.', principles: ['Let the object lead', 'Details build confidence', 'A quiet path to purchase'] },
  { id: 'nperspective', previewUrl: null, title: 'Nperspective', category: 'Web design · Digital experience', year: '2023', description: 'A new perspective on what comes next.', image: 'assets/images/nperspective.svg', link: 'projects/nperspective.html', services: ['Visual identity', 'Web design', 'Design systems'], color: '#e6cfb6', headline: 'Making space for a different perspective.', overview: 'An illustrative digital studio concept with an expressive identity and a modular website that balances personality with a clear presentation of work.', challenge: 'How might we communicate a creative point of view while making the studio’s expertise and process easy to explore?', approach: 'Build a recognizable typographic rhythm, then use a flexible grid to create moments of surprise. Keep navigation and calls to action consistent.', solution: 'An editorial homepage, project storytelling system, and a compact visual language. Warm paper tones and a confident orange accent give the concept its character.', principles: ['Personality with purpose', 'A flexible visual rhythm', 'Space for the work'] },
];

const services = [
  ['UI/UX design', 'Useful feels effortless.', 'Research, journeys, and interfaces that make complex things feel simple. Every decision starts with the people using the product.', 'User flows / Wireframes / Interface design'],
  ['Product design', 'From first thought to daily habit.', 'Shaping an idea into a coherent product experience, connecting business goals with real user needs from discovery through delivery.', 'Discovery / Product strategy / Prototyping'],
  ['Web design', 'A strong first impression. And every one after.', 'Distinctive, responsive websites with thoughtful hierarchy, strong visual systems, and a clear path through the content.', 'Art direction / Responsive UI / Developer handoff'],
  ['Mobile app design', 'Made for life on the move.', 'Focused mobile experiences that feel natural in your hand, with intuitive navigation and purposeful interactions.', 'iOS & Android / App flows / Interaction design'],
  ['Design systems', 'Consistency that makes room for growth.', 'Reusable components, clear patterns, and practical documentation that help designers and developers build together.', 'Components / Design tokens / Documentation'],
  ['AI-powered design', 'More possibilities. Thoughtful decisions.', 'AI-assisted exploration and iteration paired with human judgment. Faster ways to test ideas without losing the intent behind them.', 'Concept exploration / Workflow design / Rapid prototyping'],
  ['Visual / graphic design', 'The details make the difference.', 'A cohesive visual language across digital touchpoints, from expressive typography to thoughtful graphics and brand assets.', 'Visual identity / Digital graphics / Brand direction'],
];

if (typeof window !== 'undefined') window.PortfolioData = { site, projects, services };
if (typeof module !== 'undefined') module.exports = { site, projects, services };
